### ISSUE TITLE
Document Split Key

### ISSUE THREAD

**Issue by epmills** [symmetree-labs/zerostash#154]
The `split_key` subcommand of `0s keys generate` does not appear to be documented.

Could an example of a split key be added to [config.toml.example](https://github.com/symmetree-labs/zerostash/blob/master/config.toml.example)?

Is it possible to require a Yubikey when checking out a repository but not when committing?

My use case is the desire to commit using a plain keyfile but require a Yubikey when checking out the repository.  Something like:
```ini
# Write-only keyfile
# No prompt required, suitable for batch process
source = "plaintext"
user = "me"
password = "correct horse battery staple"
```
```ini
# Read-only or read-write keyfile
# Requires Yubikey be present and touched
source = "yubikey"
user = "me"
password = "correct horse battery staple"
slot = "slot1"
key = "hmac1"
```

**Comment by epmills** [comment]
It appears to me after investigating the source code that the current configuration cannot accommodate split keys with two-factor authentication because each key must have one source and that source could be `split_key` or `yubikey` but not both.

On the other hand, for the scenario of backing up an untrusted backup server and restoring on a trusted server, using a split key would seem acceptable.  You can't apply 2FA when restoring but on the other hand the server is trusted.

Regarding documentation, I still think it would be a good idea to provide split key examples in the same configuration file rather scouring the unit tests.  Let me know if you'd like me to take a stab at adding one or more examples of split keys to `config.toml.example`.

**Comment by rsdy** [comment]
Sorry for the lack of response here, it got buried in my inbox. You're correct, 2nd factor will not work here due to the underlying crypto.

I'm happy to accept a PR any time if you'd like to have a stab at this!

**Comment by rsdy** [comment]
Please take a look at https://github.com/symmetree-labs/zerostash/commit/bac0356728fa41348660a3210207f7b7ad23b9a6

If you think this is usable, happy to close this issue.
