### ISSUE TITLE
Well… not true :) This project works nicely with Rust stable channel.

### ISSUE THREAD

**Issue by dmilith** [symmetree-labs/zerostash#66]
All I needed was commenting out
```rust
// #![feature(test)]
```

line from bench/src/main.rs

and it works and compiles just fine on 1.45.2. Here's result from bench on my box:

```
   Compiling zerostash-bench v0.1.0 (/Projects/zerostash/bench)
    Finished release [optimized] target(s) in 2m 11s
     Running `target/release/0s-bench 4 /Projects/zerostash ../repo ../restore`
stats for path (/Projects/zerostash), seconds: 3.57139331
 * files: 2785,
 * chunks: 5139,
 * data size: 795.9273195266724
 * throughput: 220.01437938714972
 * objects: 1364
 * output size: 1210.9234237670898
 * compression ratio: 1.5213994972395348
 * meta dump time: 0.046221692
 * meta object count: 1
 * chunk reuse: 5734/5139 = 1.115781280404748

read time: 0.119582733
restore time: 2.85608005
throughput packed: 406.9424232762903
throughput unpacked: 267.47900470235254
```

**Comment by dmilith** [comment]
Did https://github.com/rsdy/zerostash/pull/67

**Comment by dmilith** [comment]
Oh I see some stuff is required for tests… :)

**Comment by rsdy** [comment]
Yes, you can build the `0s` binary, but tests require nightly. If you have any suggestions how to clean this up, that would be welcome, as benchmarks specifically do require the `#![feature(test)]`. As far as I'm aware, everything else builds on stable.

**Comment by dmilith** [comment]
If there would be a way to tell Rust to compile mod tests {} (in bench/src/main.rs) only on nightly… that would solve the problem. Just on stable those tests would be skipped… which is not a very good idea.

I also wonder about equivalent of #[bench] on stable like https://crates.io/crates/criterion which has downside - completely different API…

What do you think?

**Comment by dmilith** [comment]
I think this project is worth being on stable channel… so I'm open to help (and learn) with porting that if you like this solution :)

**Comment by dmilith** [comment]
Looks like `#![cfg_attr(test, feature(test))]` instead of `#![feature(test)]` does the job as well. Just test has to be invoked with`cargo +nightly test`. Could be solution for now, without requirement of refactoring.

**Comment by rsdy** [comment]
Yes, the thing that kept me from using `criterion` is the huge API change. Thanks for bringing this up, I'll make a new issue about the bench suite.
